### ISSUE TITLE
Suggestion: option for email notifications, all/new/none

### ISSUE THREAD

**Issue by gowestweb** [aarongreenlee/Hoth#21]
Thanks very much for Hoth. 
I have been using it via the Mura Plugin created by Greg Moser, and as a standalone reporting tool on my newest sites. In both cases, I think it would be useful if we could expand the email notification options to include emailing _all_ exceptions. When setting up a new site, or even after something goes live, I often want to know every time an error occurs, even if the same exception has been thrown and tracked once already. 

So the change would be from a boolean true/false value , to a 3-way option of  "all, new, none" ... or something like that. 
Possible? Feasible? 

thanks again, I've been telling anybody who can use it what a great system you've created in Hoth.

**Comment by aarongreenlee** [comment]
Status as of July 2016: Hoth is stable and can help you identify, track, and prioritize your ColdFusion bugs. However, I will not be investing resources in this package going forward. I had done quite a bit of ColdFusion work as a contractor working on projects for Adobe but that time is passed. If you would like to continue to grow this project please reach out to me as I would be happy to add you as a organizer.
