### ISSUE TITLE
Railo Compatibility?

### ISSUE THREAD

**Issue by jeaguilar** [aarongreenlee/Hoth#24]
Is Hoth compatible with Railo? I am running the Mura plugin version on 3.3.3.001 on OS X (Jetty) and Mura 5.6.4940. HothTracker.cfc throws the following error:

**Message:**
railo.runtime.tag.Lock.setMetaData(Ljava/lang/String;Ljava/lang/Object;)V 

**Additional:**
_Cause:_
java.lang.NoSuchMethodError

**Stacktrace:**
railo.runtime.tag.Lock.setMetaData(Ljava/lang/String;Ljava/lang/Object;)V at hothtracker_cfc$cf.udfCall(/Applications/Railo/cms.website.com/plugins/Hoth/HothTracker.cfc:251):251 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:215):215 at railo.runtime.type.UDFImpl._call(UDFImpl.java:434):434 at railo.runtime.type.UDFImpl.call(UDFImpl.java:384):384 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:738):738 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1480):1480 at hothtracker_cfc$cf.udfCall(/Applications/Railo/cms.website.com/plugins/Hoth/HothTracker.cfc:41):41 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:215):215 at railo.runtime.type.UDFImpl._call(UDFImpl.java:434):434 at railo.runtime.type.UDFImpl.call(UDFImpl.java:384):384 at railo.runtime.ComponentImpl._call(ComponentImpl.java:615):615 at railo.runtime.ComponentImpl._call(ComponentImpl.java:502):502 at railo.runtime.ComponentImpl.call(ComponentImpl.java:1815):1815 at railo.runtime.functions.other._CreateComponent.call(_CreateComponent.java:48):48 at hoth.plugin.eventhandler_cfc$cf.udfCall(/Applications/Railo/cms.website.com/plugins/Hoth/plugin/eventHandler.cfc:23):23 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:215):215 at railo.runtime.type.UDFImpl._call(UDFImpl.java:434):434 at railo.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:377):377 at railo.runtime.ComponentImpl._call(ComponentImpl.java:616):616 at railo.runtime.ComponentImpl._call(ComponentImpl.java:502):502 at railo.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1830):1830 at railo.runtime.tag.Invoke.doComponent(Invoke.java:210):210 at railo.runtime.tag.Invoke.doEndTag(Invoke.java:183):183 at plugin.pluginmanager_cfc$cf._3(/Applications/Railo/cms.website.com/requirements/mura/plugin/pluginManager.cfc:1348):1348 at plugin.pluginmanager_cfc$cf.udfCall(/Applications/Railo/cms.website.com/requirements/mura/plugin/pluginManager.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:215):215 at railo.runtime.type.UDFImpl._call(UDFImpl.java:434):434 at railo.runtime.type.UDFImpl.call(UDFImpl.java:384):384 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:738):738 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1480):1480 at plugin.pluginmanager_cfc$cf._3(/Applications/Railo/cms.website.com/requirements/mura/plugin/pluginManager.cfc:1228):1228 at plugin.pluginmanager_cfc$cf.udfCall(/Applications/Railo/cms.website.com/requirements/mura/plugin/pluginManager.cfc):-1 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:215):215 at railo.runtime.type.UDFImpl._call(UDFImpl.java:434):434 at railo.runtime.type.UDFImpl.call(UDFImpl.java:384):384 at railo.runtime.ComponentImpl._call(ComponentImpl.java:615):615 at railo.runtime.ComponentImpl._call(ComponentImpl.java:502):502 at railo.runtime.ComponentImpl.call(ComponentImpl.java:1815):1815 at railo.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:733):733 at railo.runtime.PageContextImpl.getFunction(PageContextImpl.java:1480):1480 at appcfc.onerror_include_cfm$cf.call(/Applications/Railo/cms.website.com/config/appcfc/onError_include.cfm:67):67 at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:799):799 at railo.runtime.PageContextImpl.doInclude(PageContextImpl.java:746):746 at config.appcfc.onerror_method_cfm$cf.udfCall(/Applications/Railo/cms.website.com/config/appcfc/onError_method.cfm:52):52 at railo.runtime.type.UDFImpl.implementation(UDFImpl.java:215):215 at railo.runtime.type.UDFImpl._call(UDFImpl.java:434):434 at railo.runtime.type.UDFImpl.call(UDFImpl.java:384):384 at railo.runtime.ComponentImpl._call(ComponentImpl.java:615):615 at railo.runtime.ComponentImpl._call(ComponentImpl.java:502):502 at railo.runtime.ComponentImpl.call(ComponentImpl.java:1815):1815 at railo.runtime.listener.ModernAppListener.call(ModernAppListener.java:349):349 at railo.runtime.listener.ModernAppListener.onError(ModernAppListener.java:336):336 at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2045):2045 at railo.runtime.PageContextImpl.execute(PageContextImpl.java:2002):2002 at railo.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:297):297 at railo.loader.servlet.CFMLServlet.service(CFMLServlet.java:32):32 at javax.servlet.http.HttpServlet.service(HttpServlet.java:820):820 at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534):534 at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475):475 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119):119 at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:516):516 at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226):226 at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:929):929 at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403):403 at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184):184 at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864):864 at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117):117 at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:216):216 at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:151):151 at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114):114 at org.eclipse.jetty.server.Server.handle(Server.java:352):352 at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596):596 at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1051):1051 at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590):590 at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212):212 at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426):426 at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508):508 at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34):34 at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40):40 at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:451):451 at java.lang.Thread.run(Thread.java:680):680

**Tag Context:**
_codePrintPlain_
249: 250: /** Ensure our directory structure is as expected. */ 251: lock name=VARIABLES._NAME timeout=variables.Config.getTimeToLock() type="exclusive" { 252: if (!directoryExists(variables.paths.Exceptions)) { 253: directoryCreate(variables.paths.Exceptions);
_column_ 0
_id_ ??
_line_  251
_raw_trace_ hothtracker_cfc$cf.udfCall(/Applications/Railo/cms.website.com/plugins/Hoth/HothTracker.cfc:251)
_template_ /Applications/Railo/cms.website.com/plugins/Hoth/HothTracker.cfc
_type_ cfml

I had no luck installing directly from the source instead of as a plugin. It's possible I'm seeing a Railo bug here but I'm just not sure.

**Comment by aarongreenlee** [comment]
Status as of July 2016: Hoth is stable and can help you identify, track, and prioritize your ColdFusion bugs. However, I will not be investing resources in this package going forward. I had done quite a bit of ColdFusion work as a contractor working on projects for Adobe but that time is passed. If you would like to continue to grow this project please reach out to me as I would be happy to add you as a organizer.
